/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import Physique.Data.ConfigReader;
import Physique.Data.PhysiqueDataFactory;
import java.io.File;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class Config extends javax.swing.JDialog {

    /**
     * Creates new form Config
     */
    public Config(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonToMenu = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBase = new javax.swing.JTextField();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonConfigurer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButtonGenerateTable = new javax.swing.JButton();
        jButtonAPropos = new javax.swing.JButton();
        jButtonExampleBook = new javax.swing.JButton();
        jLabelStatut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonToMenu.setText("Revenir à l'écran d'accueil");
        jButtonToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonToMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonToMenu)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonToMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Host :");

        jLabel2.setText("Base :");

        jLabel3.setText("Utilisateur :");

        jLabel4.setText("Mot de passe :");

        jButtonConfigurer.setText("Configurer");
        jButtonConfigurer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigurerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonConfigurer))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldPass, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(jTextFieldID)
                        .addComponent(jTextFieldHost)
                        .addComponent(jTextFieldBase)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfigurer)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Base de données", jPanel2);

        jButtonGenerateTable.setText("Générer les tables manquantes");
        jButtonGenerateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateTableActionPerformed(evt);
            }
        });

        jButtonAPropos.setText("A propos");
        jButtonAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAProposActionPerformed(evt);
            }
        });

        jButtonExampleBook.setText("Générer des exemples de livres");
        jButtonExampleBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExampleBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGenerateTable, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(jButtonAPropos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExampleBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonGenerateTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExampleBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButtonAPropos)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Options", jPanel3);

        jLabelStatut.setForeground(new java.awt.Color(0, 0, 0));
        jLabelStatut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStatut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelStatut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonToMenuActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonToMenuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.lecture();
    }//GEN-LAST:event_formWindowOpened

    private void jButtonConfigurerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigurerActionPerformed
        // TODO add your handling code here:
        if (this.checkconfig()) {
            File config = new File("serveur.properties");
            try {
                boolean exist = true;
                if (!config.exists()) {
                    config.createNewFile();
                    exist = false;
                }
                FileWriter fw = new FileWriter(config, false);
                fw.write("serveur.host=" + jTextFieldHost.getText() + "\nserveur.base=" + jTextFieldBase.getText() + "\nserveur.id=" + jTextFieldID.getText() + "\nserveur.pass=" + jTextFieldPass.getText());
                fw.close();
                if (!exist) {
                    jLabelStatut.setText("<html><body><font color='green'>Connexion configurée</font></body></html>");
                } else {
                    jLabelStatut.setText("<html><body><font color='green'>Connexion configurée</font> <font color='orange'>(Redémarrage nécessaire)</font></body></html>");
                }
            } catch (Exception ex) {
                //Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
                jLabelStatut.setText("<html><body><font color='red'>" + ex.getMessage() + "</font></body></html>");
            }
        } else {
            jLabelStatut.setText("<html><body><font color='red'>Veuillez remplir tous les champs</font></body></html>");
        }
    }//GEN-LAST:event_jButtonConfigurerActionPerformed

    private void jButtonGenerateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerateTableActionPerformed
        try {
            // TODO add your handling code here:
            jLabelStatut.setText("<html><body><font color='green'>Création des tables manquantes...</font></body></html>");
            PhysiqueDataFactory.getConfigDataService().generateTable();
            jLabelStatut.setText("<html><body><font color='green'>Les tables manquantes ont été créées</font></body></html>");
            JOptionPane.showMessageDialog(this, "Rappel :\nL'administrateur a été créé automatiquement si la table 'adherents' n'existait pas !\n   - Identifiant : andoria14\n   - Mot de passe : skyfall", "Information", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            jLabelStatut.setText("<html><body><font color='red'>" + ex.getMessage() + "</font></body></html>");
        }
    }//GEN-LAST:event_jButtonGenerateTableActionPerformed

    private void jButtonAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAProposActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Logiciel créé par Jonathan Drouin, étudiant en BTS IRIS - 1er année\nVersion : 1.0\nDate : 13 Mai 2013\nSite de référence : jonathan.drouin.free.fr");
    }//GEN-LAST:event_jButtonAProposActionPerformed

    private void jButtonExampleBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExampleBookActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            jLabelStatut.setText("<html><body><font color='green'>Création de livres...</font></body></html>");
            PhysiqueDataFactory.getConfigDataService().generateExample();
            jLabelStatut.setText("<html><body><font color='green'>Les livres ont été créés</font></body></html>");
        } catch (Exception ex) {
            Logger.getLogger(Config.class.getName()).log(Level.SEVERE, null, ex);
            jLabelStatut.setText("<html><body><font color='red'>" + ex.getMessage() + "</font></body></html>");
        }
    }//GEN-LAST:event_jButtonExampleBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Config.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Config dialog = new Config(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAPropos;
    private javax.swing.JButton jButtonConfigurer;
    private javax.swing.JButton jButtonExampleBook;
    private javax.swing.JButton jButtonGenerateTable;
    private javax.swing.JButton jButtonToMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelStatut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldBase;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPass;
    // End of variables declaration//GEN-END:variables

    private void lecture() {
        jTextFieldHost.setText(ConfigReader.getInstance("serveur.properties").getProperty("serveur.host"));
        jTextFieldBase.setText(ConfigReader.getInstance("serveur.properties").getProperty("serveur.base"));
        jTextFieldID.setText(ConfigReader.getInstance("serveur.properties").getProperty("serveur.id"));
        jTextFieldPass.setText(ConfigReader.getInstance("serveur.properties").getProperty("serveur.pass"));
        jLabelStatut.setText("<html><body><font color='green'>Fichier chargé</font></body></html>");
    }

    private boolean checkconfig() {
        boolean retour = false;
        if (!jTextFieldHost.getText().equals("")) {
            if (!jTextFieldBase.getText().equals("")) {
                if (!jTextFieldID.getText().equals("")) {
                    retour = true;
                }
            }
        }
        return retour;
    }
}
